### ISSUE TITLE
这条SQL在 validate 阶段报错

### ISSUE THREAD

**Issue by li-shoupeng-peng** [kaijianding/clickhouse-calcite-optimizer#4]
CREATE TABLE test_db.test_table
(
    `dt` DateTime,
    `actual_goods_cnt` Int32
)
ENGINE = MergeTree
ORDER BY dt
SETTINGS index_granularity = 8192;

SELECT
	SUM(t.ord_amount_middle) ord_amount_middle
FROM
	(
		SELECT
			t.dt dt,
			groupBitmapMerge(t.ord_amount_middle) ord_amount_middle
		FROM
			(
				SELECT
					t.dt dt,
					groupBitmapState(t.actual_goods_cnt)ord_amount_middle
				FROM
					test_db.test_table t
				WHERE
					t.dt = '2024-01-15'
				GROUP BY
					dt
			)
			t
		GROUP BY
			dt
	)
	t

报错：org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 12, column 23 to line 12, column 40: Expression 't.actual_goods_cnt' is not being grouped

原因是：private static final SqlValidator.Config VALIDATE_CONFIG = SqlValidator.Config.DEFAULT
            .withSqlConformance(SqlConformanceEnum.MYSQL_5)
            .withDefaultNullCollation(NullCollation.HIGH)
            .withIdentifierExpansion(true); 按照 MYSQL 配置了语法验证。

如果想解决这个问题，是不是就要改Parser.jj了？

**Comment by kaijianding** [comment]
sql语法只有agg不需要出现在group by里。
在`ClickhouseAggregators`里添加groupBitmapState和groupBitmapMerge。
因为一个未知的函数calcite不知道是agg还是标量Function，所以需要在某个地方标记agg列表，在这个列表之外的就是标量函数
